FROM node:22 AS build
WORKDIR /app

COPY SmtManager.Web/package*.json ./

RUN npm install

COPY SmtManager.Web/ .

RUN npm run build -- --configuration production

FROM nginx:alpine

COPY --from=build /app/dist/client/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
